@startuml

object "InspectionResponse" as ir {
  id = "21085286190ffad1248d17c4135ee56f"
  submitted_at = "2023-07-29T22:38:22Z"
}

object "Inspector" as inspector {
  id = "1234567890"
  name = "John Doe"
}

object "Store" as store {
  id = "0987654321"
  name = "John's Store"
}

object "ControlAnswer1" as answer1 {
  type = "choices"
}

object "AnswerField1" as field1 {
  sort = 1
  id = "1"
  ref = "dispocitivos_anti_inceptos"
  type = "multiple_choice"
}

object "AnswerChoice1a" as choice1a {
  label = "tela mosquitera"
  ref = "tela_mosquitera"
}

object "AnswerAttachment1a" as attachment1a {
  url = "attachments/5.png"
  type = "image"
  name = "foto ventana lateral cocina"
  size = 0
}

object "ControlAnswer2" as answer2 {
  type = "boolean"
  boolean = false
}

object "AnswerField2" as field2 {
  sort = 2
  id = "2"
  ref = "carnet_manipulacion_alimentos"
  type = "yes_no"
}

object "ControlAnswer3" as answer3 {
  type = "choices"
}

object "AnswerField3" as field3 {
  sort = 3
  id = "3"
  ref = "dispocitivos_incendios"
  type = "multiple_choice"
}

object "AnswerChoice3a" as choice3a {
  label = "extintor"
  ref = "extintor"
}

object "AnswerChoice3b" as choice3b {
  label = "manguera"
  ref = "manguera"
}

object "AnswerAttachment3a" as attachment3a {
  url = "attachments/3.png"
  type = "image"
  name = "foto extintor pasillo"
  size = 0
}

object "AnswerAttachment3b" as attachment3b {
  url = "attachments/1.png"
  type = "image"
  name = "foto extintor patio"
  size = 0
}

object "AnswerAttachment3c" as attachment3c {
  url = "attachments/2.png"
  type = "image"
  name = "foto extintor estacionamiento"
  size = 0
}

object "AnswerAttachment3d" as attachment3d {
  url = "attachments/4.png"
  type = "image"
  name = "foto manguera y extintor"
  size = 0
}

ir --> inspector
ir --> store
ir --> answer1 : answers
ir --> answer2 : answers
ir --> answer3 : answers

answer1 --> field1 : field
answer1 --> choice1a : choices
answer1 --> attachment1a : attachments

answer2 --> field2 : field

answer3 --> field3 : field
answer3 --> choice3a : choices
answer3 --> choice3b : choices
answer3 --> attachment3a : attachments
answer3 --> attachment3b : attachments
answer3 --> attachment3c : attachments
answer3 --> attachment3d : attachments

@enduml
