@startuml
!define RECTANGLE class

RECTANGLE InspectionResponse {
  - String responseId
  - Date submittedAt
  - Inspector inspector
  - Store store
  - List<ControlAnswer> answers
}

RECTANGLE Inspector {
  - String id
  - String name
}

RECTANGLE Store {
  - String id
  - String name
}

RECTANGLE ControlAnswer {
  - Field field
  - String type
  - List<Choice> choices
  - Choice choice
  - Boolean boolean
}

RECTANGLE Field {
  - int sort
  - String id
  - String ref
  - String type
}

RECTANGLE Choice {
  - String label
  - String ref
}

InspectionResponse --> Inspector
InspectionResponse --> Store
InspectionResponse --> ControlAnswer
ControlAnswer --> Field
ControlAnswer --> Choice

@enduml

