@startuml
!define RECTANGLE object

RECTANGLE InspectionResponse {
  responseId = "21085286190ffad1248d17c4135ee56f"
  submittedAt = "2023-07-29T22:38:22Z"
  inspector
  store
  answers
}

RECTANGLE Inspector {
  id = "1234567890"
  name = "John Doe"
}

RECTANGLE Store {
  id = "0987654321"
  name = "John's Store"
}

RECTANGLE ControlAnswer1 {
  field
  type = "choices"
  choices
}

RECTANGLE ControlAnswer2 {
  field
  type = "choice"
  choice
}

RECTANGLE ControlAnswer3 {
  field
  type = "boolean"
  boolean = false
}

RECTANGLE Field1 {
  sort = 1
  id = "1"
  ref = "dispocitivos_anti_inceptos"
  type = "multiple_choice"
}


RECTANGLE Field4 {
  sort = 3
  id = "3"
  ref = "dispositivos_de_incendio"
  type = "multiple_choice"
}

RECTANGLE Field2 {
  sort = 2
  id = "2"
  ref = "carnet_manipulacion_alimentos"
  type = "yes_no"
}

RECTANGLE Choice4 {
   label = "malla plastica"
   ref = "malla_plastica"
}

RECTANGLE Choice1 {
  label = "tela mosquitera"
  ref = "tela_mosquitera"
}

RECTANGLE Choice3 {
  label = "matafuegos"
    ref = "matafuegos"
}

RECTANGLE Choice2 {
  label = "cortina de aire"
  ref = "cortina_de_aire"
}



InspectionResponse --> Inspector : inspector
InspectionResponse --> Store : store
InspectionResponse --> ControlAnswer1 : answers
InspectionResponse --> ControlAnswer2 : answers
InspectionResponse --> ControlAnswer3 : answers

ControlAnswer1 --> Field1 : field
ControlAnswer1 --> Choice1 : choices
ControlAnswer2 --> Field4 : field
ControlAnswer1 --> Choice2 : choice
ControlAnswer2 --> Choice3 : choice
ControlAnswer3 --> Field2 : field

@enduml
